version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10  
  pre_build:
    commands:
      - echo Installing dependencies...
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code
      - npm install 
  post_build:
    commands:
      - echo Build completed on `date`
      - echo $CODEBUILD_SRC_DIR 
      - ls 
      - find . -type d -not -name dist -exec rm -R {} \;
      - mv dist/* .
      - ls 
      - ls ../
artifacts:
  files:
    - '**/*'
    
  