export const menus = [
    {
        id: 'dashboard',
        icon: ['fas', 'tachometer-alt'],
        img: 'icon-home.svg',
        active: 'icon-home-active.svg',
        label: 'Home',
        to: '/app',
        type: 'producer',
    },
    {
        id: 'sales',
        icon: ['fas', 'tachometer-alt'],
        img: 'dollar-sign-solid-nav.svg',
        active: 'dollar-sign-solid-active.svg',
        label: 'Sales',
        to: '/app/sales',
        type: 'producer',
    },
	{
        id: 'tracks',
        icon: ['fas', 'music'],
        img: 'icon-tracks.svg',
        active: 'icon-music-active.svg',
        label: 'Your Music',
        to: '/app/beats/manage',
        type: 'producer',
        subs: [
            {
                label: 'Beats',
                to: '/app/beats/manage',
                target: '_self',
                type: 'producer',
            },
            {
                label: 'Licenses',
                to: '/app/licenses/manage',
                target: '_self',
                type: 'producer',
            },
            {
                label: 'Sound Kits',
                to: '/app/kits/manage',
                target: '_self',
                type: 'producer',
            },
            {
                label: 'Beat Packs',
                to: '/app/beat-packs/manage',
                target: '_self',
                type: 'producer',
            },
        ],
    },
	{
        id: 'links',
        icon: ['fas', 'link'],
		img: 'icon-link.svg',
        active: 'icon-link-active.svg',
        label: 'Links',
        to: '/app/links/manage',
        type: 'producer',
        subs: [
            {
                label: 'Add new link',
                to: '/app/links/add',
                target: '_self',
                type: 'producer',
            },
            {
                label: 'Manage links',
                to: '/app/links/manage',
                target: '_self',
                type: 'producer',
            },
        ],
    },
	{
        id: 'videos',
        icon: ['fas', 'play-circle'],
		img: 'icon-youtube-active.svg',
        active: 'icon-youtube.svg',
        label: 'Videos',
        to: '/app/videos/manage',
        type: 'producer',
        subs: [
            {
                label: 'Add new video',
                to: '/app/videos/add',
                target: '_self',
                type: 'producer',
            },
            {
                label: 'Manage videos',
                to: '/app/videos/manage',
                target: '_self',
                type: 'producer',
            },
        ],
    },
	{
        id: 'analytics',
        icon: ['fas', 'chart-bar'],
        img: 'icon-chart-bar.svg',
        active: 'icon-chart-bar-active.svg',
        label: 'Analytics',
        to: '/app/analytics',
        type: 'producer',
    },
	{
        id: 'marketing',
        icon: ['fas', 'bullhorn'],
		img: 'bullhorn-solid.svg',
        active: 'bullhorn-solid-active.svg',
        label: 'Marketing',
        to: '/app/marketing/messages',
        type: 'producer',
        subs: [
            {
                label: 'Messages',
                to: '/app/marketing/messages',
                target: '_self',
                type: 'producer',
            },
            {
                label: 'Subscribers',
                to: '/app/marketing/subscribers',
                target: '_self',
                type: 'producer',
            },
            {
                label: 'Landing Pages',
                to: '/app/marketing/landing-pages',
                target: '_self',
                type: 'producer',
            },
            // {
            //     label: 'Ad Promos',
            //     to: '/app/marketing/ad-promos',
            //     target: '_self',
            // },
            {
                label: 'YouTube Uploader',
                to: '/app/marketing/youtube/uploader',
                target: '_self',
                type: 'producer',
            },
        ],
    },
    {
        id: 'profile',
        icon: ['fas', 'user-circle'],
        img: 'store-solid.svg',
        active: 'store-solid-active.svg',
        label: 'Online Store',
        to: '/app/profile/edit',
        type: 'producer',
        subs: [
            {
                label: 'Edit Profile',
                to: '/app/profile/edit',
                target: '_self',
                type: 'producer',
            },
            {
                label: 'View Profile',
                to: '/user_url',
                target: '_blank',
                type: 'producer',
            },
        ],
    },  
    {
        id: 'shopnow',
        icon: ['fas', 'chart-bar'],
        img: 'basket.svg',
        active: 'basket.svg',
        label: 'Shop Now',
        to: '/app/shopnow',
        type: 'listener',
    },
    {
        id: 'account',
        icon: ['fas', 'user'],
        img: 'ic-settings.svg',
        active: 'ic-settings-active.svg',
        label: 'Account Settings',
        to: '/app/account/info',
        type: 'both',
        subs: [
            {
                label: 'Account Info',
                to: '/app/account/info',
                target: '_self',
                type: 'both',
            },
            {
                label: 'Purchases',
                to: '/app/account/purchases',
                target: '_self',
                type: 'both',
            },
            {
                label: 'Payments',
                to: '/app/account/payments',
                target: '_self',
                type: 'both',
            },
            {
                label: 'Payouts',
                to: '/app/account/payouts',
                target: '_self',
                type: 'producer',
            },
            {
                label: 'Notifications',
                to: '/app/account/notifications',
                target: '_self',
                type: 'both',
            },
        ],
    },
    {
        id: 'upgrade',
        icon: ['fas', 'arrow-circle-up'],
		img: 'arrow-alt-circle-up.svg',
        active: 'arrow-alt-circle-up-active.svg',
        label: 'Upgrade',
        to: '/app/upgrade',
        type: 'both',
    },
]
