<?php
$data = array();
$this->load->view('home/_inc/header', $data);
?>
<body data-spy="scroll" data-target=".scrollspy" class="bg-dark" style="overflow:  auto !important">

    <!-- Preloader  -->
    <div class="loader bg-dark">
        <div class="loader-inner ball-scale-ripple-multiple ball-scale-ripple-multiple-color">
            <div></div>
            <div></div>
            <div></div>
        </div>
    </div>
    <!-- /End Preloader  -->


    <div id="page">

        <!-- ============================
             BG & Overlays
        ================================= -->

        <!-- Solid BG -->
        <div class="section-overlay bg-solid-color overlay-opacity"></div>
        <!-- /End Solid BG -->

        <div class="container-fluid">
            <div class="row">
                <!-- ============================
                     Info
                ================================= -->
                <div class="col-md-3">

                </div>
                <div id="info" class="col-md-6 text-white text-center  col-transform">
                    <div class="vert-middle">
                        <div class="">

                            <!-- Logo -->
                            <div class="p-t-b-15">
                                <img src="<?= HTTP_ASSETS ?>solid-bg/images/streamy_logo_vertical_negative_RGB.png" width="180px" alt="streamy logo">
                            </div>
                            <!-- /End Logo -->


                            <div class="text-justify">
                                <h2><span class="font-weight-200">Privacy Policy </span></h2>
                                <p>This Privacy Policy applies to Streamy's websites ("Streamy.link") and the ("Streamy or We/Our") treatment of personally identifiable information that Streamy collects when you register with one of our websites, or sign-up for a promotional offer by Streamy, and you agree to receive e-mail, SMS, and other types of electronic marketing ("Electronic Marketing"). It is important that visitors are fully informed about the use of their personal information. Streamy believes in 100% permission-based marketing. By using this website, purchasing or using the products or services on this website, or signing-up for a promotional offer by Streamy, you agree to the terms contained herein in this Privacy Policy.</p>
                                <br>
                                <h2 class="text-left"><span class="font-weight-200">What information do we collect? How is it used?</span></h2>
                                <p>This Privacy Policy also applies to you as you have agreed to receive Electronic Marketing from Streamy or our partner websites, either via e-mail, third party partner websites, or otherwise, herein collectively known as the ("Network"), by using this website or using our products or services. You agree that we may sell the non-personal identifiable information and personal identifiable information that you supply to us, and we may work with other businesses to bring select retail opportunities to our users. These businesses may include, but are not limited to: a) providers of direct marketing services and applications, including lookup and reference, data enhancement, suppression and validation; (b) e-mail marketers; and (c) telemarketers.</p>
                                <p>We may also employ other companies and individuals to perform certain functions on our behalf. Examples include sending direct and electronic mail, removing duplicate information from user lists, analyzing data, and providing marketing analysis. These agents have access to our users' personal information as needed to perform their functions for Streamy, but we do not permit them to use your personal information for any other purpose.</p>
                                <p>By typing Your name in the field provided in the final checkout process, You expressly consent and agree that Our communications with you is part of our contract. You agree to accept and receive communications from Us, including via e-mail, text message, telephone calls, and push notifications to the residential or cellular telephone number You provided to Us, as applicable. By consenting to being contacted by Streamy, You understand and agree that You may receive communications generated by automatic telephone dialing systems which may deliver prerecorded messages sent by or on behalf of Streamy, its affiliated companies or partners, regarding but not limited to: operational communications concerning Your order or use of the Streamy website or services, updates concerning new and existing features on the Streamy website; communications concerning promotions by Us or Our third-party partners; and news concerning Streamy and industry developments. Standard SMS/TEXT messaging charges applied by Your cell phone carrier will apply to SMS/TEXT messages We send. </p>
                                <p>You are not required to consent to receive SMS/TEXT messages as a condition of using the Streamy website or services.</p>
                                <p>Termination of Consent. IF YOU WISH TO OPT-OUT OF EMAILS, SMS (TEXT MESSAGES), OR OTHER COMMUNICATIONS, YOU MAY OPT-OUT BY ONE OF THE FOLLOWING UNSUBSCRIBE OPTIONS:</p>
                                <ul>
                                    <li>You may opt-out of receiving all SMS/TEXT messages from Streamy at any time by replying to one of Our SMS/TEXT messages with any of the following words “STOP,” “ARRET,” “CANCEL,” “END,” “OPT-OUT,” “OPTOUT,” “QUIT,” “REMOVE,” “TD,” “UNSUBSCRIBE” from the mobile device receiving the messages.</li>
                                </ul>
                                <p>You may also send an email to privacy@Streamy.link to stop any or all of SMS/TEXT messages, emails, and telephone calls from being sent to You by Streamy. If You choose this option, You must include Your cellular phone number or You may continue to receive SMS/TEXT messages and calls.</p>
                                <p>While We respect Your decision to opt-out, You agree and understand that opting out of receiving all SMS/TEXT messages, emails, and calls will impact Our ability to provide our service to you. </p>
                                <p>You may unsubscribe from any of our e-mail marketing programs at any time. In every e-mail communication we send, there is an unsubscribe hyperlink that allows the recipient to unsubscribe from that specific marketing program by simply clicking the hyperlink provided and following the instructions provided. We attempt to process all unsubscribe requests in a prompt fashion. However, after unsubscribing, we cannot guarantee that you will never receive another mailing from us, because we may obtain your e-mail address in the future through a different e-mail marketing program that you have opted into. However, should you ever receive another e-mail communication from Streamy you will be able to remove your e-mail address via the unsubscribe hyperlink. Streamy is able to offer its premium products and services at a competitive price, in part, based upon the willingness of our users to be contacted by our marketing partners, including affiliated third-party advertisers. By allowing Streamy to make the information you supply available to our marketing partners, you may receive free product and service information that may be of interest to you. If you are a resident of the State of California and would like to opt-out from the disclosure of your personal information to any third party for direct marketing purposes, please email us at: privacy@Streamy.link. Streamy may employ "cookies" to help customize your access to the website, and for the delivery of targeted advertisements. A cookie is a piece of data stored on your hard drive containing information about you. Cookies have many benefits to enhance your experience at our website and to facilitate the receipt of targeted advertisements. For instance, by setting a cookie on our website, a user would not have to log in a password more than once, thereby saving time while on our website. Even in the case where a user rejects a cookie, he or she may still use our website. </p>
                                <p>We use cookies to track, monitor and target the interests of our users to further enhance the experience on our website, and for subsequent advertising and/or delivery purposes. To find out more about cookies, please visit http://www.cookiecentral.com/. In addition, for the purpose of formatting and delivering future campaigns, Streamy and its partners may employ pixel tags (also known as clear gifs) to track: 1) the pages that our users visit on affiliate and/or partner websites; and 2) user opens of, and clicks on, our targeted email advertising. We reserve the right to employ user source information, including applicable category and interest(s), for the marketing of targeted e-mail messages on behalf of our clients. This source information may be shared with our third-party marketing partners. Streamy reserves the right to retain cookie and pixel tag data indefinitely. When you use our network, we automatically receive records and information on our server logs from your browser such as: (i) IP address; (ii) domain server; (iii) access times; (iv) referring website addresses; and (v) the Internet service provider ("ISP") used to access the network in order to perform troubleshooting (i.e., to help diagnose problems with our server) or administer the network. </p>
                                <p>Streamy reserves the right to provide aggregate or group data about Streamy users for lawful purposes. Aggregate or group data is data that describes the demographics, usage, or characteristics of Streamy participants as a group, without disclosing personally identifiable information. By opening an Streamy account, you agree to allow Streamy to provide such aggregate data to third parties. By agreeing to these terms, you hereby consent to the disclosure of any record or communication to any third party when Streamy, in its sole discretion, determines the disclosure to be appropriate. Additionally, when you open, preview or click on the advertising portion of our e-mails and/or those of our marketing partners and/or affiliates of Streamy, you have agreed to the terms set forth in our Privacy Policy, and agree that as a function of opening, previewing or clicking on the advertising portion of our e-mails, that you will receive new or additional marketing communications from us, our marketing partners and/or affiliates of Streamy. </p>
                                <br>
                                <h2 class="text-left"><span class="font-weight-200">Legal Requests / Questionable Activities</span></h2>
                                <p>We will cooperate with law enforcement inquiries, as well as other authorized third parties to enforce laws, such as: intellectual property rights, fraud and other rights, and to help protect you from bad actors. Therefore, in response to a verified request by law enforcement or authorized government official relating to a criminal investigation or alleged illegal activity, we can (and you authorize us to) disclose your name, city, state, telephone number, email address, usage history, IP address, access times and fraud complaints. Notwithstanding the foregoing, when we believe in good faith that the disclosure of information is necessary to prevent imminent physical harm or financial loss; or report suspected illegal activity, we will provide the necessary information as required to address the specific situation. </p>

                                <br>
                                <h2 class="text-left"><span class="font-weight-200">Further Release of Data </span></h2>
                                <p>Streamy also reserves the right to release current or past user information in the event that Streamy believes that:1) the user is using, or has used, services of Streamy in violation of the terms and conditions, to commit unlawful acts; 2) if the information is subpoenaed; 3) if Streamy is sold or acquired; or 4) when Streamy deems it necessary or appropriate including, without limitation, sharing your e-mail address with other third-parties for suppression purposes in compliance with the CAN-SPAM Act of 2003, as amended from time to time, and Federal Trade Commission enabling regulations. </p>
                                <p>In addition, by registering at the website, you agree that such act constitutes an inquiry and/or application for purposes of the Amended Telemarketing Sales Rule (16 CFR 310 et seq.), as amended from time to time (the "Rule"). Notwithstanding that your telephone number may be listed on the Federal Trade Commission's Do-Not-Call List, we retain the right to contact you via telemarketing in accordance with the Rule. </p>

                                <br>
                                <h2 class="text-left"><span class="font-weight-200">Data Security </span></h2>
                                <p>To the extent that user credit card-specific information is collected by Streamy and/or any of its affiliates and/or subsidiaries, said information will be kept in confidence and will not be shared with any third parties without the user's prior informed consent or a court order mandating release. Notwithstanding the foregoing, Streamy, its affiliates and/or subsidiaries reserve the right to share with third parties the fact that they have credit card information on file for specific users but they will not share the specific credit card information with third parties without the user's prior informed consent. </p>
                                <p>We endeavor to safeguard and protect our users' information. When users submit information at the website, their information is protected both online and offline. The privacy of your personal information is very important to us. The servers in which we store personally identifiable information are kept in a secure physical environment. Streamy has security measures in place to protect the loss, misuse, and alteration of personal information under our control. Currently, Streamy uses Secure Socket Layer Software ("SSL") to protect data and to secure any transactions. SSL encrypts information, including credit card numbers, names and addresses as they are transmitted over the Internet. Please be advised that, although we take every reasonable technological precaution available to protect your data, no data transmission over the Internet can be guaranteed to be 100% secure. Therefore, Streamy cannot warrant that your information will be absolutely secure. Any transmission of data at or through our website is at your own risk. However, access to your information is strictly limited, and not accessible to the public. Our employees are dedicated to ensuring the security and privacy of all Streamy user information.</p>

                                <br>
                                <h2 class="text-left"><span class="font-weight-200">Further Limitation on Privacy </span></h2>
                                <p>Due to the existing regulatory environment, we cannot ensure that all of your private communications and other personal information will never be disclosed in ways not otherwise described in this Privacy Policy. By way of example (without limiting the foregoing), third parties may unlawfully intercept or access transmissions or private communications, or users may abuse or misuse your personal information that they collect through the Network. Therefore, although we exceed industry standard practices to protect your privacy, we do not promise, and you should not expect, that your personal information or private communications will always remain private. </p>


                                <br>

                                <h2 class="text-left"><span class="font-weight-200"> Children</span></h2>
                                <p>Users under eighteen (18) years of age are not allowed to participate in sweepstakes or game promotions offered by Streamy. No information should be submitted to, or posted at, any Streamy website property by visitors under eighteen (18) years of age without the prior consent of their parent or guardian. Notwithstanding the foregoing, children thirteen (13) years of age and younger are not permitted to access the website, and we do not knowingly collect personal information from such children. We encourage parents and guardians to spend time online with their children and to participate and monitor the interactive activities of their children. Streamy uses reasonable efforts to comply with Children's Online Privacy Protection Act (COPPA) and Interactive Advertising Bureau (IAB) privacy guidelines. </p>
                                <p>Third Party Users may receive e-mail confirming their registration with Streamy, as well as promotional marketing of commercial products and services. </p>
                                <p>Streamy does not endorse, nor is Streamy responsible for the accuracy of, the privacy policies and/or terms and conditions of any of the advertisers and/or third parties accessible through the Streamy website. However, we reserve the right to also allow other companies, called third-party ad servers or ad networks, to serve advertisements within our Network web pages. In addition, some of our advertisers may use the services of third-party ad networks. Some of these third-party ad networks may place a persistent cookie on your computer. Doing this allows the third-party ad network to recognize your computer each time they send you an online advertisement. In this way, third-party ad networks may compile information about where you, or others who are using your computer, saw their advertisements and determine which ads are clicked on. This information allows a third-party ad network to deliver targeted advertisements that they believe will be of most interest to you. Streamy does not have access to or control of the cookies that may be placed by the third-party ad servers or third-party ad networks. Those third-party ad networks that use persistent cookies may offer you a way to opt-out of ad targeting. You may find more information at the Website of either the individual third-party ad network or the Network Advertising Initiative www.networkadvertising.org.</p>
                                <br>

                                <h2 class="text-left"><span class="font-weight-200">Donations Made Through Streamy’ Website </span></h2>
                                <p>From time to time, We may offer the opportunity for Our customers and users of Our Website, the opportunity to donate to various charities and charitable organizations. Donations are voluntary and are not required to complete a purchase of Streamy’ products or services. Should You choose to make a donation through Our website, Your information, limited to Your name and email address, will be provided to the charity You chose. By making a donation through Our website, you agree to be bound by that charity’s terms and conditions and privacy policy. </p>

                                <br>

                                <h2 class="text-left"><span class="font-weight-200">Other Websites and Your Privacy </span></h2>
                                <p>Streamy Network may contain links to other websites. Once you select a link that takes you to another website, you are subject to the privacy policy of the website containing that page. Please note that these other websites may have privacy policies that differ from this one in the level of security, use of cookies and use of personally identifiable information. We have no control over any information you choose to provide to those websites. </p>

                                <br>

                                <h2 class="text-left"><span class="font-weight-200"> International Users</span></h2>
                                <p>Personal data that you have voluntarily entered electronically is delivered to servers located in the United States. By using our Network or any of our Advertiser's websites, you consent to the transfer of this data, and to our use of such data as outlined in this Privacy Policy and as allowed under the laws of the United States. </p>

                                <br>

                                <h2><span class="font-weight-200"> Legal Disclaimer</span></h2>
                                <p>We disclaim and you agree that we will not be liable to you for any damages caused by acts or events beyond our reasonable control including, without limitation, acts of God, fires, floods, acts of terrorism, wars, civil disturbances, sabotage, accidents, labor disputes, governmental actions, and failures or delays of transportation that result in our disclosure of your personally identifiable information. </p>

                                <br>

                                <h2 class="text-left"><span class="font-weight-200">Your Acceptance of These Terms </span></h2>
                                <p>By using this website, including, without limitation, signing up for offers and/or continuing to receive information from Streamy, you agree to the Streamy Privacy Policy. We reserve the right, at our discretion, to change, modify, add, and/or remove portions of this Privacy Policy at any time. All Privacy Policy changes will take effect immediately upon their posting on Streamy websites. Please check this page periodically for changes. Your use of the Streamy websites or acceptance of our e-mails following the posting of changes to these terms will mean that you accept these changes and agree to continue receiving e-mails from us. If you do not agree to the terms of this Privacy Policy, please unsubscribe by emailing privacy@Streamy.link. If you have any questions about this Privacy Policy, please contact us at privacy@Streamy.link. </p>

                                <br>

                                <h2 class="text-left"><span class="font-weight-200"> </span></h2>
                                <p>Streamy and Streamy.link, are registered marks and are owned and operated by Streamy, Inc. and its related entities and subsidiaries. </p>

                                <br>

<!--                                    <h2><span class="font-weight-200"> </span></h2>
                                    <p></p>

                                    <br>

                                    <h2><span class="font-weight-200"> </span></h2>
                                    <p></p>

                                    <br>

                                    <h2><span class="font-weight-200"> </span></h2>
                                    <p></p>

                                    <br>-->
                            </div>


                            <!--                                <div class="p-t-b-15">
                                                                 Headline & Description 
                                                                <h2><span class="font-weight-200">Privacy Policy </span></h2>
                            
                                                                <p>This Privacy Policy applies to Streamy's websites ("Streamy.link") and the ("Streamy or We/Our") treatment of personally identifiable information that Streamy collects when you register with one of our websites, or sign-up for a promotional offer by Streamy, and you agree to receive e-mail, SMS, and other types of electronic marketing ("Electronic Marketing"). It is important that visitors are fully informed about the use of their personal information. Streamy believes in 100% permission-based marketing. By using this website, purchasing or using the products or services on this website, or signing-up for a promotional offer by Streamy, you agree to the terms contained herein in this Privacy Policy.</p>
                                                                 /End Headline & Description 
                                                            </div>-->

                            <!-- /End Buttons -->

                            <!-- Social Media Links -->
                            <div class="p-t-b-30">
                                <p>
                                    <a href="https://www.instagram.com/streamy.link" target="_blank" class="link-white"><i
                                            class="fa fa-instagram"></i>Join the fam on Instgram!</a>&nbsp&nbsp&nbsp    
                                    <!--               <a href="#" class="link-white">Legal Content</a>-->
                                                     <!--<a href="https://plus.google.com" class="link-white"><i
                                                        class="fa fa-google-plus"></i></a>
                                                    <a href="https://www.behance.net/egotype" class="link-white"><i
                                                        class="fa fa-behance"></i></a> -->
                                </p>
                            </div>
                            <!-- Social Media Links -->
                            <!-- Social Media Links -->
                            <div class="p-t-b-1">
                                <p>
                                    ©2020 Streamy LLC. All Rights Reserved.
                                </p><br><br>
                            </div>
                            <!-- Social Media Links -->

                        </div>
                    </div>
                </div>
                <div class="col-md-3">

                </div>
            </div>
        </div>

    </div>
    <!-- /#page -->
    <div id="photoswipe"></div>

    <!-- Scripts -->
    <script src="<?= HTTP_ASSETS ?>solid-bg/js/plugins/jquery-1.12.4.min.js"></script>
    <script src="<?= HTTP_ASSETS ?>solid-bg/js/plugins/bootstrap.min.js"></script>
    <script src="<?= HTTP_ASSETS ?>solid-bg/js/plugins/scrollreveal.min.js"></script>
    <script src="<?= HTTP_ASSETS ?>solid-bg/js/plugins/contact-form.js"></script>
    <script src="<?= HTTP_ASSETS ?>solid-bg/js/plugins/newsletter-form.js"></script>
    <script src="<?= HTTP_ASSETS ?>solid-bg/js/plugins/jquery.ajaxchimp.min.js"></script>
    <script src="<?= HTTP_ASSETS ?>solid-bg/js/plugins/photoswipe/photoswipe.min.js"></script>
    <script src="<?= HTTP_ASSETS ?>solid-bg/js/plugins/photoswipe/photoswipe-ui-default.min.js"></script>
    <script src="<?= HTTP_ASSETS ?>solid-bg/js/plugins/jquery.countdown.min.js"></script>
    <script src="<?= HTTP_ASSETS ?>solid-bg/js/plugins/prefixfree.min.js"></script>
    <script src="<?= HTTP_ASSETS ?>jquery-validation-1.19.1/dist/jquery.validate.min.js"></script>
    <script src="<?= HTTP_ASSETS ?>jquery-validation-1.19.1/dist/additional-methods.min.js"></script>

    <script> var urlBase = "<?= base_url(); ?>";</script>

    <!-- Custom Script -->
    <script src="<?= HTTP_ASSETS ?>solid-bg/js/custom.js"></script>


</body>
</html>
